// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ospvelfzpuunfjdlicfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zcHZlbGZ6cHV1bmZqZGxpY2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTEwOTcsImV4cCI6MjA3MTQ2NzA5N30.BgjvTKtzyz3CUzAESSTIgHbfXPu62iVcTCTDq-NVv1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});