export const BAD_WORDS = [
    'MERDA', 'PUTA', 'COLLONS', 'JODER', 'CABRO', 'CABRONA', 'FILLDEPUTA', 'GILIPOLLAS',
    'IMBECIL', 'IDIOTA', 'ESTUPID', 'FOLL', 'FOLLAR', 'TITOT', 'MAMON', 'CAPULLO',
    'COYONS', 'HOSTIA', 'OSTIA', 'MERDER', 'MERD', 'CAC', 'CACA', 'PIXA', 'CONY',
    'FOTRE', 'FOTUT', 'FUTUT', 'PUTO', 'PUT', 'MARICA', 'MARICON', 'BUJARRON',
    'BOJARRON', 'BORD', 'ZORRA', 'PORC', 'PORCA', 'PUTES', 'MEUCA',
    'BAGASSA', 'DROPA', 'DROP', 'LLEPACULS', 'LLEPAFILS', 'TANCA', 'TANCAT',
    'MAMADA', 'MAMAR', 'XONA', 'XIRLA', 'NATA', 'SEMENT', 'VERRA', 'VERRO',
    'BARRUFET', 'CAGAR', 'CAGADA', 'JODOR', 'JODRE', 'FOTRES', 'COLLONADA'
];
